apiVersion: v1
kind: Service
metadata:
  name: helloworld-go
spec:
  selector:
    tier: frontend
  clusterIP: 10.99.132.220
  externalTrafficPolicy: Cluster
  ports:
  - name: myport
    port: 8037
    protocol: TCP
    targetPort: 3040
  externalIPs:
  - 118.138.240.202
  type: LoadBalancer
  
